### ISSUE TITLE
Cakephp 3.6 gets HTTP ERROR 500 after install

### ISSUE THREAD

**Issue by Mark-Lister** [WyriHaximus/Ratchet#137]
After installing the plugin I can no longer get to my website even though I'm running the sever on apache. Do I need to configure something sorry if this is a stupid question.

Apache gives this
`[Mon Jun 03 01:03:48.329486 2019] [:error] [pid 9442] [client ************] PHP Fatal error:  Uncaught TypeError: Return value of Doctrine\\Common\\Annotations\\AnnotationRegistry::registerLoader() must be an instance of Doctrine\\Common\\Annotations\\void, none returned in /var/www/html/team/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:117\nStack trace:\n#0 /var/www/html/team/vendor/wyrihaximus/doctrine-annotation-autoloader/src/bootstrap.php(7): Doctrine\\Common\\Annotations\\AnnotationRegistry::registerLoader(Object(Closure))\n#1 /var/www/html/team/vendor/composer/autoload_real.php(66): require('/var/www/html/t...')\n#2 /var/www/html/team/vendor/composer/autoload_real.php(56): composerRequire6cd38df98a9609a1e80253b51a07dc04('34a3b220523648a...', '/var/www/html/t...')\n#3 /var/www/html/team/vendor/autoload.php(7): ComposerAutoloaderInit6cd38df98a9609a1e80253b51a07dc04::getLoader()\n#4 /var/www/html/team/webroot/index.php(27): require('/var/www/html/t...')\n#5 {main}\n  thrown in /var/www/html/team/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 117`

Thanks!

**Comment by Mark-Lister** [comment]
Apache was setup for different php version
