### ISSUE TITLE
Class React\EventLoop\Factory not found in WebsocketShell.php

### ISSUE THREAD

**Issue by WisdomProductionz** [WyriHaximus/Ratchet#37]
Im trying to start the server but keep getting Class React\EventLoop\Factory not found in WebsocketShell.php. This is my first time using composer and loading plugins with cakephp so it may be something very simple im not doing but its driving me crazy, any help would be appreciated.
Here is my bootstrap.php file in Plugin/Ratchet/Config/

```
require APP . '/Vendor/autoload.php';

CakePlugin::load('Ratchet', ['bootstrap' => true]);
CakePlugin::load('RatchetCommands', ['bootstrap' => true]);
CakePlugin::load('RatchetModelPush');

Configure::write('Ratchet', [
	'Client' => [
		'retryDelay' => 5000, // Not the best option but it speeds up development
		'maxRetries' => 25, // Keep on trying! (Also not the best option)
	],
	'Connection' => [
		'websocket' => [
			'address' => '0.0.0.0',
			'port' => 11001,
		],
		'external' => [
			'hostname' => 'localhost',
			'port' => 80,
			'path' => 'websocket',
			'secure' => false,
		],
		'keepaliveInterval' => 23, // Why 23? Because NGINX kills after 30 seconds, set to 0 to disable
	],
]);

App::uses('CakeEventManager', 'Event');

App::uses('RatchetKeepAliveListener', 'Ratchet.Event');
CakeEventManager::instance()->attach(new RatchetKeepAliveListener());

App::uses('PcntlListener', 'Ratchet.Event');
CakeEventManager::instance()->attach(new PcntlListener());
```

And here is the error

```
Fatal error: Class 'React\EventLoop\Factory' not found in C:\wamp\www\app\Plugin\Ratchet\Console\Command\WebsocketShell.php on lin
e 51

Call Stack:
    0.0002     238384   1. {main}() C:\wamp\www\app\Console\cake.php:0
    0.0008     340216   2. ShellDispatcher::run() C:\wamp\www\app\Console\cake.php:47
    0.0158    2378448   3. ShellDispatcher->dispatch() C:\wamp\www\lib\Cake\Console\ShellDispatcher.php:66
    0.0189    2754696   4. Shell->runCommand() C:\wamp\www\lib\Cake\Console\ShellDispatcher.php:209
    0.0280    3690528   5. WebsocketShell->start() C:\wamp\www\lib\Cake\Console\Shell.php:445

Fatal Error Error: Class 'React\EventLoop\Factory' not found in [C:\wamp\www\app\Plugin\Ratchet\Console\Command\WebsocketShell.php
, line 51]
```

**Comment by WisdomProductionz** [comment]
I have just seen the last issue someone had a similar problem as me but i have just tried there fix and it still gives me the same error

**Comment by WyriHaximus** [comment]
bootstrap.php looks good to me, did you run `composer install`?

**Comment by WyriHaximus** [comment]
Also can you gist your composer.json?

**Comment by WisdomProductionz** [comment]
Thank you for your reply. I have sorted out the previous problem, it was a stupid mistake i was making. Now i have a new error which i cannot figure out, it is:

```
Error: Could not bind to tcp://:: Failed to parse address ":"
#0 C:\wamp\www\app\Plugin\Ratchet\Console\Command\WebsocketShell.php(63): React\Socket\Server->listen(NULL, NULL)
#1 C:\wamp\www\lib\Cake\Console\Shell.php(445): WebsocketShell->start()
#2 C:\wamp\www\lib\Cake\Console\ShellDispatcher.php(209): Shell->runCommand('start', Array)
#3 C:\wamp\www\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#4 C:\wamp\www\app\Console\cake.php(47): ShellDispatcher::run(Array)
#5 {main}
```

**Comment by WyriHaximus** [comment]
Odd since your bootstrap looks fine. If you add this on line 58, you should see if the config is getting there as it should:
```php
debug(Configure::read('Ratchet'));
```

**Comment by WisdomProductionz** [comment]
This is the message i get when i add the debug:

```
Welcome to CakePHP v2.6.1 Console
---------------------------------------------------------------
App : app
Path: C:\wamp\www\app\
---------------------------------------------------------------
Your configuration doesn't seem to support 'ext-libevent'. It is highly reccomended that you install and configure it as it provides significant perfo
rmance gains over stream select!
\app\Plugin\Ratchet\Console\Command\WebsocketShell.php (line 58)
########## DEBUG ##########
null
###########################
Error: Could not bind to tcp://:: Failed to parse address ":"
#0 C:\wamp\www\app\Plugin\Ratchet\Console\Command\WebsocketShell.php(63): React\Socket\Server->listen(NULL, NULL)
#1 C:\wamp\www\lib\Cake\Console\Shell.php(445): WebsocketShell->start()
#2 C:\wamp\www\lib\Cake\Console\ShellDispatcher.php(209): Shell->runCommand('start', Array)
#3 C:\wamp\www\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#4 C:\wamp\www\app\Console\cake.php(47): ShellDispatcher::run(Array)
#5 {main}
```

Besides the Plugin/Ratchet/Config/bootstrap.php is there anything else i need to add to cakephp. 

app/Config/bootstrap.php has
``` 
CakePlugin::loadAll();
```

app/Config/core.php has 
```
require dirname(__DIR__) . '/Vendor/autoload.php';
```
at the very top of the file and if i remove either of them i get the error:

```
Error: Plugin Ratchet could not be found.
#0 C:\wamp\www\lib\Cake\Core\App.php(227): CakePlugin::path('Ratchet')
#1 C:\wamp\www\lib\Cake\Core\App.php(549): App::path('Console/Command', 'Ratchet')
#2 [internal function]: App::load('WebsocketShell')
#3 [internal function]: spl_autoload_call('WebsocketShell')
#4 C:\wamp\www\lib\Cake\Console\ShellDispatcher.php(249): class_exists('WebsocketShell')
#5 C:\wamp\www\lib\Cake\Console\ShellDispatcher.php(200): ShellDispatcher->_getShell('Ratchet.websock...')
#6 C:\wamp\www\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 C:\wamp\www\app\Console\cake.php(47): ShellDispatcher::run(Array)
#8 {main}
```

Am i doing everything correct?

Thank you for your patience

**Comment by WisdomProductionz** [comment]
Hopefully this should be the last the question lol thank you for baring with me, i have sorted the last errors by installing the zmq extension but now im getting this one:

```
Welcome to CakePHP v2.6.1 Console
---------------------------------------------------------------
App : app
Path: C:\wamp\www\app\
---------------------------------------------------------------
Your configuration doesn't seem to support 'ext-libevent'. It is highly reccomended that you install and configure it as it provides significant perfo
rmance gains over stream select!
\app\Plugin\Ratchet\Console\Command\WebsocketShell.php (line 59)
########## DEBUG ##########
array(
        'Client' => array(
                'retryDelay' => (int) 5000,
                'maxRetries' => (int) 25
        ),
        'Connection' => array(
                'websocket' => array(
                        'port' => '*****',
                        'address' => '0.0.0.0'
                ),
                'external' => array(
                        'port' => '*****',
                        'hostname' => 'localhost',
                        'path' => 'websocket',
                        'secure' => false
                ),
                'keepaliveInterval' => (int) 23
        )
)
###########################
[1424041948.1214] Event begin: Rachet.WampServer.construct
Your configuration doesn't seem to support 'ext-pcntl'. It is highly recomended that you install and configure it as it provides OS signaling support!

[1424041948.1252] Event end: Rachet.WampServer.construct
Warning Error: stream_select(): cannot represent a stream of type ZMQ_FD as a select()able descriptor in [C:\wamp\www\app\Vendor\r
eact\event-loop\StreamSelectLoop.php, line 255]
```

**Comment by WyriHaximus** [comment]
Did you only install `Ratchet` or only the `RachetCommands` plugin? Even better can you list all installed plugins for this project? Been Googling the error a bit and maybe this thread could help you out? https://groups.google.com/forum/#!msg/ratchet-php/-0AeSrdoKDI/2AeJ-MVakfcJ

**Comment by WisdomProductionz** [comment]
The app/Plugins folder has:
```
Ratchet
RatchetCommands
RatchetModelPush
```
I also came across that thread but i wondered if there was a solution to the error without having to switch to Wamp 32bit

**Comment by WyriHaximus** [comment]
Ah right that that explains why ZMQ came in. To be honest I wouldn't have a clue, running everything in vagrant boxes on directly on linux and not using PHP on windows at all.

**Comment by fvelcker** [comment]
I had all these problems when I added these lines into the plugin bootstrap (as I suspect WisdomProductionz has done).
```php
require APP . '/Vendor/autoload.php';
CakePlugin::load('Ratchet', ['bootstrap' => true]);
```
and these into my app bootstrap
```php
CakePlugin::loadAll();
```

And it worked perfectly when I add these lines into the my app bootstrap only.
require APP . '/Vendor/autoload.php';
CakePlugin::load('Ratchet', ['bootstrap' => true]);
